language: go
go:
  - 1.8.x
sudo: required
install:
  - go get github.com/spf13/hugo
script:
  - hugo version
  - hugo -v
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: www.neavey.net
  region: eu-west-1
  local-dir: public
  skip_cleanup: true
  on:
     branch: master
#    repo: patrickn/neaveynet-hugo
notifications:
  email:
    on_failure: always
