baseurl = "https://neaveynet.github.io/"
languageCode = "en-gb"
title = "neavey.net - Adventure Miles"
# Enable comments by entering your Disqus shortname
disqusShortname = "neaveynet"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-87135551-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    author = "Adventure Miles"
    bio = "Travelling the world, two weeks at a time."
    location = "Bristol, UK"
    #site_description = "Site Description"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/logo.png"
    #logo = "css/images/logo.png"

    # Format dates with Go's time formatting
    date_format = "02-01-2006"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option to
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/Neavey"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "patrickn"
    instagram       = "pneavey"
    youtube         = "PatrickN0"
    googleplus      = "PatrickN0"
    facebook        = "pneave"
    twitter         = "neavey"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    #categories = true
    #tags = true
    tag_cloud = true
